### PR TITLE
[translation] Italian language translation-update

### PR DESCRIPTION
**Pull request by Alexwilmac**
Corrected a serious spelling mistakes (Spostare sù). Reviewed many lines.

### CODE REVIEW

**Comment by jbleyel** [comment]
Please fix the conflict and pull again.
Thanks

**Comment by Alexwilmac** [comment]
What conflict? The old file is 10 y.o. and is full of useless lines and a serious Italian mistake. I've been using my file, whom you didn't merged, for about 3 years now, in many images without problems.
In the old file there are many references to "/media/TREKSTOR/enigma2-svn/crossepg/trunk/src/enigma2/python/plugin.py" which are useless.
It's not clear what conflicts should I solve. If you like a fresh, effective translation of this plugin, I think you should merge it. Otherwise tell me if I entitled to create a new branch. Only, I don't want to avoid recognising the first author, whose work was a basis for my review. 
Which is the best to proceed?

**Comment by jbleyel** [comment]
Do you have the latest and correct translation on your fork?

**Comment by Alexwilmac** [comment]
I confess that, particularly when I started doing pulling requests I was completely new at GitHub and it seemed that this file I sent was completely forgotten. Also, my friend nunigaia told me that there were some inconsistencies in the repo which caused the new translation to not be included in our OBH and BH images. So I gave up trying.
Now, I don't remember how I created this pull request. Do you think it's better to start everything over and creating a new fork?
In this case, should I start from here:
https://github.com/E2OpenPlugins/e2openplugin-CrossEPG/tree/master/contrib/po/it/LC_MESSAGES
and open a new fork there?

**Pull request closed without merging**
